# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 151a0af8ef56ae21fde0ac769a7944ba9c325bba3f0f74ce4be71afd693e4a17866c7c7e152c90483a5d6814d48bc1271f0f23cde02d1247e7eb2f606c6e1939

test:
  secret_key_base: 93dcce296ef5620076fb4911d5e8dede48b80247ec8225a70bc6aab5672140ac5f522504683dc0defd618ee0c1ba5373255a81f78e6fa48e53d250903215f488

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
